### ISSUE TITLE
Multiple V2s or V1s

### ISSUE THREAD

**Issue by Eno423** [SirLynix/obs-kinect#18]
Hello, 

I am currently using a V2 kinect with OBS awesomely (thanks by the way)

I wanted to ask you something else though. I know you are working on multiple streams from multiple connect units. Are you doing anything to combine those pointclouds? 

Im interested in this from a 3d Scanning aspect. I currently use V1s and V2s for 3d scanning & have gotten decent results. 

I tried messing with the SDK and multiple kinect streams but havent been able to sync the clouds up well enough to grab a REALLY good scan. 

Sorry to intrude on the OBS thread but didnt know of a way to contact you

**Comment by SirLynix** [comment]
Hello. Glad you find this plugin helpful!

I'm not really working on combining multiple Kinect streams, just on using multiple devices at the same time simultaneously.
I suppose that when you're using 3D scanning you need to know precisely where is every camera (in order to project/reproject the depth points) in a similar way to shadow mapping in rendering. Kinect may help a little bit with this with face detection/skeletal detection since it may gives all the Kinect some kind of common reference.

As far as I know, you can't use multiple Kinect v2 with official Kinect SDK, but libfreenect2 does support it (although the Kinect for Xbox one is really heavy on USB and probably requires some PCI-E USB extensions to have many).

So yeah, I think it may be possible to try to build some projection/view matrix for each Kinect but that sounds a bit complicated and out of my skill range unfortunately.
